# Generated by Django 5.2.17 on 2026-09-10 19:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('terminal_instant_sales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('terminal_payout', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gas_lottery_sales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gas_lottery_payout', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bodega_ai_lottery_sales', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bodega_ai_lottery_payout', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('terminal_instant_sales__gte', 0)), name='lottery_terminal_sales_nonnegative'), models.CheckConstraint(condition=models.Q(('terminal_payout__gte', 0)), name='lottery_terminal_payout_nonnegative'), models.CheckConstraint(condition=models.Q(('gas_lottery_sales__gte', 0)), name='lottery_gas_sales_nonnegative'), models.CheckConstraint(condition=models.Q(('gas_lottery_payout__gte', 0)), name='lottery_gas_payout_nonnegative'), models.CheckConstraint(condition=models.Q(('bodega_ai_lottery_sales__gte', 0)), name='lottery_bodega_sales_nonnegative'), models.CheckConstraint(condition=models.Q(('bodega_ai_lottery_payout__gte', 0)), name='lottery_bodega_payout_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ScratchOffReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('opening_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(249)])),
                ('closing_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(249)])),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_off_readings', to='reports.lotteryreport')),
            ],
            options={
                'ordering': ['slot_number'],
                'constraints': [models.UniqueConstraint(fields=('report', 'slot_number'), name='lottery_unique_report_slot'), models.CheckConstraint(condition=models.Q(('slot_number__gte', 1), ('slot_number__lte', 20)), name='lottery_slot_number_valid'), models.CheckConstraint(condition=models.Q(('opening_number__isnull', True), models.Q(('opening_number__gte', 0), ('opening_number__lte', 249)), _connector='OR'), name='lottery_opening_number_valid'), models.CheckConstraint(condition=models.Q(('closing_number__isnull', True), models.Q(('closing_number__gte', 0), ('closing_number__lte', 249)), _connector='OR'), name='lottery_closing_number_valid'), models.CheckConstraint(condition=models.Q(('ticket_price__gte', 0)), name='lottery_ticket_price_nonnegative')],
            },
        ),
    ]
