# Generated by Django 5.2.17 on 2026-09-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_lotteryledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('close_type', models.CharField(choices=[('day', 'Day close'), ('shift', 'Shift close')], max_length=5)),
                ('close_label', models.CharField(blank=True, max_length=80)),
                ('lottery_terminal_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lottery_terminal_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_card_actual_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_net_difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_lottery_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_lottery_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_phone_card_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bodega_gas_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gas_cash_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gas_lottery_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gas_lottery_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gas_card_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tickets', models.JSONField(default=list)),
                ('vendor_payouts', models.JSONField(default=list)),
                ('safe_drops', models.JSONField(default=list)),
                ('scratch_offs', models.JSONField(default=list)),
                ('calculated_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
