# Generated by Django 5.2.17 on 2026-09-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ticket', 'Ticket'), ('vendor_payout', 'Vendor payout'), ('safe_drop', 'Safe drop')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='reports.dailyreport')),
            ],
            options={
                'ordering': ['item_type', 'position', 'id'],
                'indexes': [models.Index(fields=['report', 'item_type'], name='reports_rep_report__4ff77e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='report_line_item_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ScratchOffRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('last_night_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starting_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ending_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_roll_counter', models.PositiveSmallIntegerField(default=1)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_off_rolls', to='reports.dailyreport')),
            ],
            options={
                'ordering': ['slot_number'],
                'constraints': [models.UniqueConstraint(fields=('report', 'slot_number'), name='unique_report_scratch_slot'), models.CheckConstraint(condition=models.Q(('slot_number__gte', 1), ('slot_number__lte', 20)), name='report_scratch_slot_range'), models.CheckConstraint(condition=models.Q(('new_roll_counter__gte', 1)), name='report_scratch_roll_counter_positive')],
            },
        ),
    ]
